project_id = "gqkqxvyburugkwvapvst"

[functions."ai-chat/agents/addition-agent"]
verify_jwt = false

[functions."ai-chat/agents/categorize-message"]
verify_jwt = false

[functions."ai-chat/agents/conversation-agent"]
verify_jwt = false