// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqkqxvyburugkwvapvst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxa3F4dnlidXJ1Z2t3dmFwdnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NTIwNjEsImV4cCI6MjA3MDUyODA2MX0.zfc9F84q4Wz_uf43ylwPS6d1fQe1tP6X3aY30YMBKsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});